package topfactors.dao.entity;
// Generated Jul 20, 2019 10:58:06 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

import topfactors.common.base.DateAudit;

/**
 * Experience generated by hbm2java
 */
@Entity
@Table(name = "experience", catalog = "topfactors")
public class Experience extends DateAudit {

	private static final long serialVersionUID = 5998478930545979020L;
	private Integer id;
	private String experienceName;
	private String experienceUrl;
	private Set<RecruitmentPost> recruitmentPosts = new HashSet<RecruitmentPost>(0);

	public Experience() {
	}

	public Experience(String experienceName, String experienceUrl, Set<RecruitmentPost> recruitmentPosts) {
		this.experienceName = experienceName;
		this.experienceUrl = experienceUrl;
		this.recruitmentPosts = recruitmentPosts;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "experience_name", length = 50)
	public String getExperienceName() {
		return this.experienceName;
	}

	public void setExperienceName(String experienceName) {
		this.experienceName = experienceName;
	}

	@Column(name = "experience_url", length = 50)
	public String getExperienceUrl() {
		return this.experienceUrl;
	}

	public void setExperienceUrl(String experienceUrl) {
		this.experienceUrl = experienceUrl;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "recruitment_post_experience", catalog = "topfactors", joinColumns = {
			@JoinColumn(name = "experience_id", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "recruitment_post_id", nullable = false, updatable = false) })
	public Set<RecruitmentPost> getRecruitmentPosts() {
		return this.recruitmentPosts;
	}

	public void setRecruitmentPosts(Set<RecruitmentPost> recruitmentPosts) {
		this.recruitmentPosts = recruitmentPosts;
	}

}
