package topfactors.dao.entity;
// Generated Jul 20, 2019 10:58:06 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import topfactors.common.base.DateAudit;

/**
 * LoginHistory generated by hbm2java
 */
@Entity
@Table(name = "login_history", catalog = "topfactors")
public class LoginHistory extends DateAudit {

	private static final long serialVersionUID = -8845878282787527892L;
	private Long id;
	private AppUser appUser;
	private String accessToken;
	private Boolean isRemembered = false;

	public LoginHistory() {
	}

	public LoginHistory(AppUser appUser, String accessToken) {
		this.appUser = appUser;
		this.accessToken = accessToken;
	}

	public LoginHistory(AppUser appUser, String accessToken, Boolean isRemembered) {
		this.appUser = appUser;
		this.accessToken = accessToken;
		this.isRemembered = isRemembered;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public AppUser getAppUser() {
		return this.appUser;
	}

	public void setAppUser(AppUser appUser) {
		this.appUser = appUser;
	}

	@Column(name = "accessToken", nullable = false, length = 65535)
	public String getAccessToken() {
		return this.accessToken;
	}

	public void setAccessToken(String accessToken) {
		this.accessToken = accessToken;
	}

	@Column(name = "is_remembered")
	public Boolean getIsRemembered() {
		return this.isRemembered;
	}

	public void setIsRemembered(Boolean isRemembered) {
		this.isRemembered = isRemembered;
	}

}
