package topfactors.dao.entity;
// Generated Jul 20, 2019 10:58:06 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SkillDetail generated by hbm2java
 */
@Entity
@Table(name = "skill_detail", catalog = "topfactors")
public class SkillDetail implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6842894372963698310L;
	private int id;
	private Skill skill;
	private String skillDetailName;
	private Set<EvalutionDetail> evalutionDetails = new HashSet<EvalutionDetail>(0);

	public SkillDetail() {
	}

	public SkillDetail(int id, Skill skill, String skillDetailName) {
		this.id = id;
		this.skill = skill;
		this.skillDetailName = skillDetailName;
	}

	public SkillDetail(int id, Skill skill, String skillDetailName, Set<EvalutionDetail> evalutionDetails) {
		this.id = id;
		this.skill = skill;
		this.skillDetailName = skillDetailName;
		this.evalutionDetails = evalutionDetails;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "skill_id", nullable = false)
	public Skill getSkill() {
		return this.skill;
	}

	public void setSkill(Skill skill) {
		this.skill = skill;
	}

	@Column(name = "skill_detail_name", nullable = false, length = 100)
	public String getSkillDetailName() {
		return this.skillDetailName;
	}

	public void setSkillDetailName(String skillDetailName) {
		this.skillDetailName = skillDetailName;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "evalution_skill", catalog = "topfactors", joinColumns = {
			@JoinColumn(name = "skill_detail_id", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "evalution_detail_id", nullable = false, updatable = false) })
	public Set<EvalutionDetail> getEvalutionDetails() {
		return this.evalutionDetails;
	}

	public void setEvalutionDetails(Set<EvalutionDetail> evalutionDetails) {
		this.evalutionDetails = evalutionDetails;
	}

}
