package topfactors.dao.entity;
// Generated Jul 20, 2019 10:58:06 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TypeOfBusiness generated by hbm2java
 */
@Entity
@Table(name = "type_of_business", catalog = "topfactors")
public class TypeOfBusiness implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3577039929892249872L;
	private Integer id;
	private String typeOfBusinessName;
	private Set<Company> companies = new HashSet<Company>(0);

	public TypeOfBusiness() {
	}

	public TypeOfBusiness(String typeOfBusinessName, Set<Company> companies) {
		this.typeOfBusinessName = typeOfBusinessName;
		this.companies = companies;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "type_of_business_name", length = 100)
	public String getTypeOfBusinessName() {
		return this.typeOfBusinessName;
	}

	public void setTypeOfBusinessName(String typeOfBusinessName) {
		this.typeOfBusinessName = typeOfBusinessName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "typeOfBusiness")
	public Set<Company> getCompanies() {
		return this.companies;
	}

	public void setCompanies(Set<Company> companies) {
		this.companies = companies;
	}

}
