package topfactors.dao.entity;
// Generated Jul 20, 2019 10:58:06 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import topfactors.common.base.UserDateAudit;

/**
 * UserOtp generated by hbm2java
 */
@Entity
@Table(name = "user_otp", catalog = "topfactors")
public class UserOtp extends UserDateAudit {

	private static final long serialVersionUID = -7331825222601950254L;
	private Long id;
	private AppUser appUser;
	private String otp;
	private Boolean isEnable;

	public UserOtp() {
	}

	public UserOtp(AppUser appUser, String otp, Boolean isEnable) {
		this.appUser = appUser;
		this.otp = otp;
		this.isEnable = isEnable;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id")
	public AppUser getAppUser() {
		return this.appUser;
	}

	public void setAppUser(AppUser appUser) {
		this.appUser = appUser;
	}

	@Column(name = "otp", length = 8)
	public String getOtp() {
		return this.otp;
	}

	public void setOtp(String otp) {
		this.otp = otp;
	}

	@Column(name = "is_enable")
	public Boolean getIsEnable() {
		return this.isEnable;
	}

	public void setIsEnable(Boolean isEnable) {
		this.isEnable = isEnable;
	}

}
